# Pandas

In [1]:
import pandas as pd

In [2]:
## Series
data = [1,2,3,4,5]
series = pd.Series(data)
print(f"Series\n{series}")
print(type(series))

Series
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [3]:
## Creating Series from dictonary

dict_data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(dict_data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
nums = [1,2,3,4,5]
roman = ['i', 'ii', 'iii', 'iv', 'v']
pd.Series(roman,nums)

1      i
2     ii
3    iii
4     iv
5      v
dtype: str

In [5]:
## Dataframe

### Creating from Dictonary of Lists

data = {
    'Name':['Aahish', 'Manav'],
    'Age':[24,23],
    'City':['Gaya','Bengaluru']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru
<class 'pandas.DataFrame'>

In [6]:
### Creating from List of Dictonaries

data = [
    {'Name':'Aahish','Age':24, 'City':'Gaya'},
    {'Name':'Manav', 'Age':23, 'City':'Bengaluru'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru
<class 'pandas.DataFrame'>

In [7]:
## CSV reader
file_path = '../../resources/datasets/Sales-Data-Analysis.csv'

df1 = pd.read_csv(file_path)
df1.head(5)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [8]:
df1.tail(5)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
249,10709,28-12-2022,Sides & Other,4.99,200.40,Drive-thru,Gift Card,Walter Muller,Berlin
250,10710,29-12-2022,Burgers,12.99,754.43,Drive-thru,Gift Card,Walter Muller,Berlin
251,10711,29-12-2022,Chicken Sandwiches,9.95,281.41,Drive-thru,Gift Card,Walter Muller,Berlin
252,10712,29-12-2022,Fries,3.49,630.37,Drive-thru,Gift Card,Walter Muller,Berlin
253,10713,29-12-2022,Beverages,2.95,677.97,Drive-thru,Gift Card,Walter Muller,Berlin

In [9]:
## Accessing the data
df

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru

In [10]:
df['Name']

0    Aahish
1     Manav
Name: Name, dtype: str

In [11]:
df.loc[0]

Name    Aahish
Age         24
City      Gaya
Name: 0, dtype: object

In [12]:
df.loc[1]

Name        Manav
Age            23
City    Bengaluru
Name: 1, dtype: object

In [13]:
df.iloc[1]

Name        Manav
Age            23
City    Bengaluru
Name: 1, dtype: object

In [14]:
df.iloc[0]

Name    Aahish
Age         24
City      Gaya
Name: 0, dtype: object

In [15]:
## Accessing a specified element
print(df.at[1,'Age'])

23

In [16]:
print(df.iat[0,0])

Aahish

In [17]:
print(df.iat[1,2])

Bengaluru

In [18]:
df

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru

In [19]:
## Data Manipulation with DataFrames

### Adding the column
df['Salary'] = [150000,170000]
df

     Name  Age       City  Salary
0  Aahish   24       Gaya  150000
1   Manav   23  Bengaluru  170000

In [20]:
### Removing the cloumn
df.drop('Salary') ## default value for axis is 0 and it checks the rows.

KeyError: "['Salary'] not found in axis"

In [21]:
df.drop('Salary',axis=1)

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru

In [22]:
df

     Name  Age       City  Salary
0  Aahish   24       Gaya  150000
1   Manav   23  Bengaluru  170000

In [23]:
df.drop('Salary',axis=1, inplace=True)

In [24]:
df

     Name  Age       City
0  Aahish   24       Gaya
1   Manav   23  Bengaluru

In [25]:
df['Age'] = df['Age'] + 1
df

     Name  Age       City
0  Aahish   25       Gaya
1   Manav   24  Bengaluru

In [26]:
df1.dtypes

Order ID            int64
Date                  str
Product               str
Price             float64
Quantity          float64
Purchase Type         str
Payment Method        str
Manager               str
City                  str
dtype: object

In [27]:
df1.describe()

           Order ID       Price    Quantity
count    254.000000  254.000000  254.000000
mean   10584.133858    7.102323  460.611457
std       75.889181    4.341855  214.888699
min    10452.000000    2.950000  200.400000
25%    10520.250000    3.490000  201.010000
50%    10583.500000    4.990000  538.880000
75%    10649.750000    9.950000  677.440000
max    10713.000000   29.050000  754.430000

In [28]:
df1.groupby('City')['Price'].mean()

City
Berlin    6.874000
Lisbon    7.288267
London    6.947333
Madrid    7.213478
Paris     7.081429
Name: Price, dtype: float64

In [29]:
df1.groupby('Manager')['Price'].mean()

Manager
       Pablo Perez     7.110000
       Remy Monet      3.220000
Joao    Silva         10.994000
Joao Silva             7.023571
Pablo    Perez         4.990000
Pablo   Perez          3.490000
Pablo  Perez           3.490000
Pablo Perez            7.502222
Remy     Monet         4.990000
Remy    Monet          3.490000
Remy Monet             7.640000
Tom      Jackson       3.490000
Tom Jackson            6.994054
Walter Muller          6.874000
Name: Price, dtype: float64

In [30]:
df1.groupby('Payment Method')['Price'].sum()

Payment Method
Cash           528.54
Credit Card    895.99
Gift Card      379.46
Name: Price, dtype: float64

In [31]:
df1.groupby('Product')['Price'].sum()

Product
Beverages             147.50
Burgers               675.48
Chicken Sandwiches    536.50
Fries                 200.00
Sides & Other         244.51
Name: Price, dtype: float64