# Data Manipulation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../resources/datasets/sales_data.csv')

In [3]:
df.head(5)

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Customer_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64.0,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38.0,Female,Cash,1.0,No,291478.48,195130.45,96348.03
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33.0,Female,Cash,2.0,No,267196.41,190035.08,77161.33
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38.0,Male,Cash,4.0,No,339742.47,280612.56,59129.91
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28.0,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46

In [4]:
df.tail()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Customer_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit
95,1096,2025-04-06,Monitor,Electronics,5,2009.76,NaN,East,Retail,31.0,Female,Debit Card,3.0,No,8039.04,6708.87,1330.17
96,1097,2025-04-07,Monitor,Accessories,5,2348.74,NaN,West,Online,NaN,Male,UPI,1.0,Yes,9982.14,7776.90,2205.24
97,1098,2025-04-08,Headphones,Accessories,7,41218.73,5.0,North,Retail,63.0,Male,Cash,NaN,No,274104.55,162279.20,111825.35
98,1099,2025-04-09,Laptop,Accessories,9,18329.44,20.0,East,Online,NaN,Female,Credit Card,NaN,No,131971.97,106968.61,25003.36
99,1100,2025-04-10,Headphones,Accessories,9,6789.50,10.0,North,Online,62.0,Female,Debit Card,3.0,Yes,54994.95,38289.10,16705.85

In [5]:
df.describe()

,Order_ID,Quantity,Unit_Price,Discount_Pct,Customer_Age,Customer_Satisfaction,Revenue,Cost,Profit
count,100.000000,100.000000,100.000000,90.000000,90.000000,90.000000,100.000000,100.000000,90.000000
mean,1050.500000,5.220000,26825.622600,10.944444,40.111111,2.877778,123897.554100,83844.472100,40226.674556
std,29.011492,3.010353,14565.548014,7.415988,13.210010,1.412845,108390.354274,74503.835959,37914.275779
min,1001.000000,1.000000,750.550000,0.000000,18.000000,1.000000,3827.800000,2586.360000,907.040000
25%,1025.750000,2.750000,14945.547500,5.000000,29.000000,2.000000,29183.605000,18995.795000,8703.417500
50%,1050.500000,5.000000,28887.385000,10.000000,39.000000,3.000000,84655.115000,59944.435000,24950.020000
75%,1075.250000,8.000000,39855.305000,20.000000,50.750000,4.000000,196094.682500,134160.497500,66758.185000
max,1100.000000,10.000000,49507.670000,20.000000,64.000000,5.000000,366313.840000,283509.600000,147680.970000

In [6]:
df.dtypes

Order_ID                   int64
Order_Date                   str
Product                      str
Category                     str
Quantity                   int64
Unit_Price               float64
Discount_Pct             float64
Region                       str
Sales_Channel                str
Customer_Age             float64
Customer_Gender              str
Payment_Method               str
Customer_Satisfaction    float64
Returned                     str
Revenue                  float64
Cost                     float64
Profit                   float64
dtype: object

In [7]:
## Hadnling missing values
df.isnull()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Customer_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
98,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().any()

Order_ID                 False
Order_Date               False
Product                  False
Category                 False
Quantity                 False
Unit_Price               False
Discount_Pct              True
Region                   False
Sales_Channel            False
Customer_Age              True
Customer_Gender          False
Payment_Method            True
Customer_Satisfaction     True
Returned                 False
Revenue                  False
Cost                     False
Profit                    True
dtype: bool

In [9]:
df.isnull().sum()

Order_ID                  0
Order_Date                0
Product                   0
Category                  0
Quantity                  0
Unit_Price                0
Discount_Pct             10
Region                    0
Sales_Channel             0
Customer_Age             10
Customer_Gender           0
Payment_Method           10
Customer_Satisfaction    10
Returned                  0
Revenue                   0
Cost                      0
Profit                   10
dtype: int64

In [10]:
df.fillna(0)

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Customer_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64.0,Male,0,1.0,Yes,71143.48,46246.80,24896.68
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38.0,Female,Cash,1.0,No,291478.48,195130.45,96348.03
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,0.0,East,Retail,33.0,Female,Cash,2.0,No,267196.41,190035.08,77161.33
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38.0,Male,Cash,4.0,No,339742.47,280612.56,59129.91
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28.0,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2025-04-06,Monitor,Electronics,5,2009.76,0.0,East,Retail,31.0,Female,Debit Card,3.0,No,8039.04,6708.87,1330.17
96,1097,2025-04-07,Monitor,Accessories,5,2348.74,0.0,West,Online,0.0,Male,UPI,1.0,Yes,9982.14,7776.90,2205.24
97,1098,2025-04-08,Headphones,Accessories,7,41218.73,5.0,North,Retail,63.0,Male,Cash,0.0,No,274104.55,162279.20,111825.35
98,1099,2025-04-09,Laptop,Accessories,9,18329.44,20.0,East,Online,0.0,Female,Credit Card,0.0,No,131971.97,106968.61,25003.36
99,1100,2025-04-10,Headphones,Accessories,9,6789.50,10.0,North,Online,62.0,Female,Debit Card,3.0,Yes,54994.95,38289.10,16705.85

In [11]:
df_filled = df.fillna(0)

In [12]:
## filling missing values with the mean of the column
df['Profit_fillNA'] = df['Profit'].fillna(df['Profit'].mean())

In [13]:
df.head(20)

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Customer_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit,Profit_fillNA
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64.0,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68,24896.680000
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38.0,Female,Cash,1.0,No,291478.48,195130.45,96348.03,96348.030000
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33.0,Female,Cash,2.0,No,267196.41,190035.08,77161.33,77161.330000
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38.0,Male,Cash,4.0,No,339742.47,280612.56,59129.91,59129.910000
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28.0,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46,80525.460000
5,1006,2025-01-06,Mouse,Electronics,1,32280.57,20.0,West,Online,54.0,Female,UPI,NaN,No,25824.46,16891.42,8933.04,8933.040000
6,1007,2025-01-07,Keyboard,Accessories,1,4664.93,15.0,North,Retail,53.0,Female,NaN,5.0,No,3965.19,3058.15,907.04,907.040000
7,1008,2025-01-08,Keyboard,Electronics,9,8500.62,20.0,South,Online,52.0,Female,Cash,4.0,No,61204.46,41965.78,19238.68,19238.680000
8,1009,2025-01-09,Keyboard,Accessories,9,44978.43,15.0,South,Online,36.0,Female,Debit Card,1.0,No,344084.99,212431.69,131653.30,131653.300000
9,1010,2025-01-10,Headphones,Accessories,4,30518.24,10.0,South,Online,37.0,Male,Debit Card,4.0,No,109865.66,75338.38,NaN,40226.674556
10,1011,2025-01-11,Monitor,Accessories,9,955.25,NaN,South,Online,35.0,Female,UPI,2.0,No,7307.66,4328.01,2979.65,2979.650000
11,1012,2025-01-12,Keyboard,Electronics,3,5522.84,20.0,South,Online,64.0,Male,Cash,3.0,No,13254.82,7991.54,5263.28,5263.280000
12,1013,2025-01-13,Webcam,Electronics,7,33343.34,5.0,East,Online,58.0,Female,Credit Card,1.0,No,221733.21,155104.67,66628.54,66628.540000
13,1014,2025-01-14,Headphones,Electronics,6,750.55,15.0,North,Retail,31.0,Female,UPI,5.0,No,3827.80,2586.36,1241.44,1241.440000
14,1015,2025-01-15,Mouse,Electronics,8,8460.00,5.0,East,Online,NaN,Female,Credit Card,2.0,No,64296.00,53009.08,11286.92,11286.920000
15,1016,2025-01-16,Monitor,Accessories,9,27662.32,10.0,West,Retail,NaN,Female,NaN,4.0,No,224064.79,147595.55,76469.24,76469.240000
16,1017,2025-01-17,Webcam,Electronics,5,34748.81,0.0,South,Online,18.0,Female,Debit Card,2.0,No,173744.05,125821.36,47922.69,47922.690000
17,1018,2025-01-18,Webcam,Electronics,1,32772.08,10.0,North,Retail,20.0,Male,UPI,1.0,No,29494.87,21816.74,7678.13,7678.130000
18,1019,2025-01-19,Mouse,Electronics,3,11601.33,15.0,South,Retail,33.0,Male,NaN,NaN,No,29583.39,16387.08,13196.31,13196.310000
19,1020,2025-01-20,Monitor,Electronics,10,35752.87,5.0,North,Retail,40.0,Female,Credit Card,3.0,No,339652.26,254420.33,85231.93,85231.930000

In [14]:
df.dtypes

Order_ID                   int64
Order_Date                   str
Product                      str
Category                     str
Quantity                   int64
Unit_Price               float64
Discount_Pct             float64
Region                       str
Sales_Channel                str
Customer_Age             float64
Customer_Gender              str
Payment_Method               str
Customer_Satisfaction    float64
Returned                     str
Revenue                  float64
Cost                     float64
Profit                   float64
Profit_fillNA            float64
dtype: object

In [15]:
## Reanaming columns
df = df.rename(columns={'Customer_Age':'Cust_Age'})

In [16]:
df.head()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Cust_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit,Profit_fillNA
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64.0,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68,24896.68
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38.0,Female,Cash,1.0,No,291478.48,195130.45,96348.03,96348.03
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33.0,Female,Cash,2.0,No,267196.41,190035.08,77161.33,77161.33
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38.0,Male,Cash,4.0,No,339742.47,280612.56,59129.91,59129.91
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28.0,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46,80525.46

In [17]:
df['Cust_Age'] = df['Cust_Age'].fillna(df['Cust_Age'].mean()).astype(int)

In [18]:
df.head()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Cust_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit,Profit_fillNA
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68,24896.68
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38,Female,Cash,1.0,No,291478.48,195130.45,96348.03,96348.03
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33,Female,Cash,2.0,No,267196.41,190035.08,77161.33,77161.33
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38,Male,Cash,4.0,No,339742.47,280612.56,59129.91,59129.91
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46,80525.46

In [19]:
df.describe()

,Order_ID,Quantity,Unit_Price,Discount_Pct,Cust_Age,Customer_Satisfaction,Revenue,Cost,Profit,Profit_fillNA
count,100.000000,100.000000,100.000000,90.000000,100.000000,90.000000,100.000000,100.000000,90.000000,100.000000
mean,1050.500000,5.220000,26825.622600,10.944444,40.100000,2.877778,123897.554100,83844.472100,40226.674556,40226.674556
std,29.011492,3.010353,14565.548014,7.415988,12.525126,1.412845,108390.354274,74503.835959,37914.275779,35948.450100
min,1001.000000,1.000000,750.550000,0.000000,18.000000,1.000000,3827.800000,2586.360000,907.040000,907.040000
25%,1025.750000,2.750000,14945.547500,5.000000,30.000000,2.000000,29183.605000,18995.795000,8703.417500,9734.910000
50%,1050.500000,5.000000,28887.385000,10.000000,40.000000,3.000000,84655.115000,59944.435000,24950.020000,30429.040000
75%,1075.250000,8.000000,39855.305000,20.000000,50.000000,4.000000,196094.682500,134160.497500,66758.185000,64062.150000
max,1100.000000,10.000000,49507.670000,20.000000,64.000000,5.000000,366313.840000,283509.600000,147680.970000,147680.970000

In [20]:
df.dtypes

Order_ID                   int64
Order_Date                   str
Product                      str
Category                     str
Quantity                   int64
Unit_Price               float64
Discount_Pct             float64
Region                       str
Sales_Channel                str
Cust_Age                   int64
Customer_Gender              str
Payment_Method               str
Customer_Satisfaction    float64
Returned                     str
Revenue                  float64
Cost                     float64
Profit                   float64
Profit_fillNA            float64
dtype: object

In [21]:
df['New_Price'] = df['Unit_Price'].apply(lambda x:x+x*0.1)

In [22]:
df.head()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Cust_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit,Profit_fillNA,New_Price
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68,24896.68,19564.457
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38,Female,Cash,1.0,No,291478.48,195130.45,96348.03,96348.03,40078.291
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33,Female,Cash,2.0,No,267196.41,190035.08,77161.33,77161.33,49397.656
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38,Male,Cash,4.0,No,339742.47,280612.56,59129.91,59129.91,48851.858
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46,80525.46,43014.224

In [23]:
## Data Aggregating and Grouping
df.head()

,Order_ID,Order_Date,Product,Category,Quantity,Unit_Price,Discount_Pct,Region,Sales_Channel,Cust_Age,Customer_Gender,Payment_Method,Customer_Satisfaction,Returned,Revenue,Cost,Profit,Profit_fillNA,New_Price
0,1001,2025-01-01,Monitor,Electronics,4,17785.87,0.0,South,Online,64,Male,NaN,1.0,Yes,71143.48,46246.80,24896.68,24896.68,19564.457
1,1002,2025-01-02,Headphones,Electronics,10,36434.81,20.0,East,Retail,38,Female,Cash,1.0,No,291478.48,195130.45,96348.03,96348.03,40078.291
2,1003,2025-01-03,Keyboard,Electronics,7,44906.96,NaN,East,Retail,33,Female,Cash,2.0,No,267196.41,190035.08,77161.33,77161.33,49397.656
3,1004,2025-01-04,Headphones,Electronics,9,44410.78,15.0,North,Online,38,Male,Cash,4.0,No,339742.47,280612.56,59129.91,59129.91,48851.858
4,1005,2025-01-05,Headphones,Electronics,7,39103.84,15.0,South,Retail,28,Male,Cash,1.0,Yes,232667.85,152142.39,80525.46,80525.46,43014.224

In [24]:
grouped_mean = df.groupby('Category')['Profit'].mean()
print(grouped_mean)

Category
Accessories    39854.460000
Electronics    40474.817593
Name: Profit, dtype: float64

In [25]:
product_group = df.groupby('Product')['Profit'].mean()
print(product_group)

Product
Headphones    46118.678750
Keyboard      30934.088000
Laptop        44548.883000
Monitor       38626.778696
Mouse         43304.025882
Webcam        35934.842143
Name: Profit, dtype: float64

In [26]:
quantity_group = df.groupby('Product')['Quantity'].sum()
print(quantity_group)

Product
Headphones    109
Keyboard       48
Laptop         74
Monitor       127
Mouse          86
Webcam         78
Name: Quantity, dtype: int64

In [27]:
price_group = df.groupby('Product')['Unit_Price'].mean()
print(price_group)

Product
Headphones    24458.534118
Keyboard      22330.737273
Laptop        22394.225455
Monitor       24177.180800
Mouse         31023.592105
Webcam        34171.460000
Name: Unit_Price, dtype: float64

In [28]:
print(df['Unit_Price'].mean())

26825.6226

In [29]:
grouped_sum = df.groupby(['Product','Region'])['Profit'].sum()
print(grouped_sum)

Product     Region
Headphones  East      225768.45
            North     320182.45
            South      80525.46
            West      111422.50
Keyboard    East      107587.36
            North       7881.09
            South     176546.51
            West       17325.92
Laptop      East       25003.36
            North     273692.02
            South      44653.56
            West      102139.89
Monitor     East      152530.89
            North     328105.65
            South     132967.20
            West      274812.17
Mouse       East      261861.57
            North      56197.20
            South     207639.95
            West      210469.72
Webcam      East      207521.07
            North     145846.39
            South     135017.01
            West       14703.32
Name: Profit, dtype: float64

In [30]:
## aggregate multiple functions
grouped_agg = df.groupby('Region')['Revenue'].agg(['mean','sum','count'])
grouped_agg

                 mean         sum  count
Region
East    143879.501739  3309228.54     23
North   120107.078824  4083640.68     34
South   132182.345294  2247099.87     17
West    105761.012308  2749786.32     26

In [31]:
### Merging and joining Dataframes
df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})

In [32]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [33]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [34]:
pd.merge(df1,df2,on='Key',how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [35]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [36]:
pd.merge(df1,df2,on='Key',how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [37]:
pd.merge(df1,df2,on='Key',how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6