## Nominal Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a dataframe

df = pd.DataFrame({
    'color':['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [5]:
df.head(6)

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [6]:
## create an instance of OneHotencoder

encoder = OneHotEncoder()

In [7]:
## perform fit and tranform

encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [9]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [11]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [12]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [14]:
## for new data
encoder.transform([['blue']]).toarray()

a:\Nexus\Coding\Data-Science-AI\Udemy-Course\envs\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [18]:
pd.concat([df,encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0