## Nominal Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a dataframe

df = pd.DataFrame({
    'color':['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [5]:
df.head(6)

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [6]:
## create an instance of OneHotencoder

encoder = OneHotEncoder()

In [7]:
## perform fit and tranform

encoder.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [9]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [11]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [12]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [14]:
## for new data
encoder.transform([['blue']]).toarray()

a:\Nexus\Coding\Data-Science-AI\Udemy-Course\envs\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [18]:
pd.concat([df,encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

## Label Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
## Create a simple dataframe 
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
lbl_encoder = LabelEncoder()

In [5]:
lbl_encoder.fit_transform(df[['color']])

a:\Nexus\Coding\Data-Science-AI\learning-intelligence\envs\data-ai\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [6]:
lbl_encoder.transform([['red']])

a:\Nexus\Coding\Data-Science-AI\learning-intelligence\envs\data-ai\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

## Ordinal Encoding

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df = pd.DataFrame({
    'size':['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [9]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [10]:
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [11]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [12]:
encoder.transform([['small']])

a:\Nexus\Coding\Data-Science-AI\learning-intelligence\envs\data-ai\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

## Target Guided Ordinal Encoding

In [1]:
import pandas as pd

In [2]:
## create dataframe

df = pd.DataFrame({
    'City':['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'Price':[200, 150, 300, 250, 180, 320 ]
})

In [3]:
df

       City  Price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [4]:
df.groupby('City')['Price'].mean()

City
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: Price, dtype: float64

In [5]:
mean_price = df.groupby('City')['Price'].mean().to_dict()

In [6]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [7]:
df['City_Encoded'] = df['City'].map(mean_price)

In [8]:
df

       City  Price  City_Encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [9]:
df[['Price', 'City_Encoded']]

   Price  City_Encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [10]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
df = pd.DataFrame(sns.load_dataset('tips'))

In [12]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
mean_total_bill = df.groupby('time')['total_bill'].mean().to_dict()

In [14]:
mean_total_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [15]:
df['encoded_time'] = df['time'].map(mean_total_bill)

In [16]:
df

     total_bill   tip     sex smoker   day    time  size encoded_time
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [17]:
df[['total_bill', 'encoded_time']]

     total_bill encoded_time
0         16.99    20.797159
1         10.34    20.797159
2         21.01    20.797159
3         23.68    20.797159
4         24.59    20.797159
..          ...          ...
239       29.03    20.797159
240       27.18    20.797159
241       22.67    20.797159
242       17.82    20.797159
243       18.78    20.797159

[244 rows x 2 columns]